name: Test
on:
  push:
  pull_request:
jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Run tests with coverage
        run: make pytest-cov
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          coveralls --finish ||:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Codacy Finished
        run: |
          curl -sfL https://coverage.codacy.com/get.sh > codacy
          bash codacy final || :
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  deploy:
    needs: [check, test]
    runs-on: ubuntu-latest
    environment: pypi
    permissions: { contents: write, id-token: write, packages: write }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN || github.token }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install
        run: |
          sudo apt-get install -yqq pandoc
          pip install -r .meta/requirements-build.txt
          make build .dockerignore Dockerfile snapcraft.yaml
      - id: dist
        uses: casperdcl/deploy-pypi@v2
        with:
          gpg_key: ${{ secrets.GPG_KEY }}
          upload: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
      - id: collect_assets
        name: Collect assets
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo docker_tags=latest,${GITHUB_REF/refs\/tags\/v/} >> $GITHUB_OUTPUT
            echo snap_channel=stable,candidate,edge >> $GITHUB_OUTPUT
          elif test "$GITHUB_REF" = refs/heads/master; then
            echo docker_tags=master >> $GITHUB_OUTPUT
            echo snap_channel=candidate,edge >> $GITHUB_OUTPUT
          elif test "$GITHUB_REF" = refs/heads/devel; then
            echo docker_tags=devel >> $GITHUB_OUTPUT
            echo snap_channel=edge >> $GITHUB_OUTPUT
          fi
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        name: Release
        run: |
          changelog=$(git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD)
          tag="${GITHUB_REF#refs/tags/}"
          gh release create --title "tqdm $tag stable" --draft --notes "$changelog" "$tag" dist/${{ steps.dist.outputs.whl }} dist/${{ steps.dist.outputs.whl_asc }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: snapcore/action-build@v1
        id: snap_build
      - if: github.event_name == 'push' && steps.collect_assets.outputs.snap_channel
        uses: snapcore/action-publish@v1
        with:
          snap: ${{ steps.snap_build.outputs.snap }}
          release: ${{ steps.collect_assets.outputs.snap_channel }}
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_TOKEN }}
      - name: Docker build push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          tags: ${{ steps.collect_assets.outputs.docker_tags }}
          password: ${{ secrets.DOCKER_PWD }}
          username: ${{ secrets.DOCKER_USR }}
          no_push: ${{ steps.collect_assets.outputs.docker_tags == '' }}
      - name: Docker push GitHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}/tqdm
          tags: ${{ steps.collect_assets.outputs.docker_tags }}
          password: ${{ github.token }}
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
          no_push: ${{ steps.collect_assets.outputs.docker_tags == '' }}
